<?php require_once('common/html_start.php'); ?>
<?php require_once('common/header.php'); ?>
<?php require_once('common/sidebar.php'); ?>
<?php require_once('common/category.php'); ?>
<?php require_once('common/feature.php'); ?>
<?php require_once('common/banners.php'); ?>
<?php require_once('common/latest.php'); ?>
<?php require_once('common/blog.php'); ?>
<?php require_once('common/footer.php'); ?>
<?php require_once('common/html_end.php'); ?>